name: mmmogpg
channels:
  - conda-forge
dependencies:
  - make
  - cmake=3.27.6
  - python=3.11
  - boost=1.84.0
  - eigen=3.4.0
  - python-devtools=0.9.0
  - pybind11
  - pip
  - pip:
    - numpy==1.23.3
    - stopit==1.1.2
